### ISSUE TITLE
생성시간이 너무 오래걸립니다.

### ISSUE THREAD

**Issue by gjh4245** [Taeu/Style-Your-Hair#4]
안녕하세요. 좋은 모델을 공유해주셔서 감사합니다.

모델을 테스트해보려고 소스/타겟 사진을 넣고 실행해봤더니

결과 생성까지 시간이 너무 오래 걸렸습니다.

혹시 원래 이렇게 오래 걸리는건가요? 아니면 제가 착각한 부분이 있을까요?

![hair_issue](https://user-images.githubusercontent.com/110454617/182325862-5590ac8d-3ecb-4530-a2a5-778b498607ab.JPG)

**Comment by myoons** [comment]
device 를 cpu 로 돌리신 것 같네요. source 와 target 의 조합마다 편차가 있겠지만, NVIDIA GeForce RTX 3090 기준 3분 50초 정도 소요됩니다.

cpu (12th Gen Intel(R) Core(TM) i7-12700K) 로 돌렸을 때는 첫번째 사진의 W+ Embedding 과정 (첨부해주신 사진의 4시간 24분 걸리시는 과정) 50분 정도 소요되네요.

**Comment by gjh4245** [comment]
답변해주셔서 감사합니다!

**Comment by myoons** [comment]
Issue 닫겠습니다. 감사합니다. :)
